### ISSUE TITLE
ModuleNotFoundError: No module named 'voc12'

### ISSUE THREAD

**Issue by jainie-max** [weijiawu/DiffuMask#3]
Thanks for your great work! There is no module voc12 when I train the affinitynet?

**Comment by weijiawu** [comment]
Thank you for your attention. I have made the necessary updates to the file in voc12. If you have any other questions or need further assistance, please feel free to ask.

**Comment by jainie-max** [comment]
Thanks!

**Comment by jainie-max** [comment]
Thanks !

**Comment by jainie-max** [comment]
Sorry to trouble you again! It seems that there are missing some prompts for specify categor (VOC) in the generate anything file , e.g. bicycle and motorbike.  How should I modify them?
